name: dbt_proj_test_1
version: 1.0.0
config-version: 2
profile: dbt_proj_test_1
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_proj_test_1:
    +materialized: view
