dbt_proj_test_1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'Not Needed'
      user: 'Not Needed'
      password: 'Not Needed'
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: RAUNIT_T20_DBT
      schema: T20_DATA_TRANSFORM
      
    prod:
      type: snowflake
      account: 'Not Needed'
      user: 'Not Needed'
      password: 'Not Needed'
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: RAUNIT_T20_DBT
      schema: T20_DATA_TRANSFORM_PROD